# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PaniniJ
email: info@paninij.org
description: >
  PaniniJ is an easy-to-integrate Java extension for safer and more modular
  concurrent programming.
baseurl: ""
url: "https://paninij.github.io"
twitter_username: paninij
github_username:  paninij

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true


exclude:
  - Gemfile
  - Gemfile.lock

keep_files:
  - javadoc

# Declare collections, and make sure that files are output:
collections:
  docs:
    output: true
  setups:
    output: true
  papers:
    output: true
  man:
    output: true

# Set default layout for each collection.
defaults:
  - scope:
      type: docs
      path: ""
    values:
      layout: page
  - scope:
      type: setups
      path: ""
    values:
      layout: page
  - scope:
      type: papers
      path: ""
    values:
      layout: paper
  - scope:
      type: man
      path: ""
    values:
      layout: man/page
